pages/account/.php, pages/product.php
Removed unused config implement
=> Removed unused config implement

helper/geo-vpn.sub.php, index.php
=> Added working vpn detection

index.php
=> Dynamic title

.github/master.yml
=> Added master cicd

.github/workflows/master.yml, .github/workflows/pre-live-cicd-service.yml
=> Fixed cicd

.github/workflows/master.yml, sitemap.xml
=> Updated sitemap

.github/workflows/master.yml
=> Added git stash to updater

error/400/404.html, include/footer-normal.php, index.php, pages/account/.php, pages/advertisement.php, pages/contact.php, pages/legal/cookie-consent.php, pages/legal/imprint.php, pages/legal/legal-notice.php, pages/legal/privacy-policy.php, pages/legal/terms-of-service.php
Changed all mails from gmail to main mailer
=> Changed all mails from gmail to main mailer

pages/language.php
=> Fixed broken rdc in lang

index.php
Added static vertical ad placement //just experimental
=> Added static vertical ad placement //just experimental

include/footer-normal.php
=> Small fix on footer lang

index.php, pages/account/.php, pages/account/helper/account.edit.php
Removed ads, fixed username change
=> Removed ads, fixed username change

pages/account/.php, pages/account/helper/apikey.req.php
It now actually works without unprepared statements
=> Actually working status page

pages/status/api/callback.php
When doing some localhost testing I found that because I was using PDO exclusive things in a non PDO statement it failed, I fixed these bugs.
=> Fixed status API

pages/account/.php
=> updated acc

include/footer-normal.php, include/header-normal.php
removed underline on footer, added pl1 to header
=> removed underline on footer, added pl1 to header

include/header-normal.php, index.php, pages/account/.php
small changes on left side header
=> small changes on left side header

include/header-normal.php
=> Fixed link issue

index.php
=> Hotfix for header

index.php
=> Hotfix second modal

index.php, pages/upload2.php
=> Not sure what I changed

include/cModal.html, index.php
=> Hotfix for broken analytics

include/cModal.html
=> Another hotfix smh

include/cModal.html, index.php
Smh Im so bad it should be fixed now
=> Smh Im so bad it should be fixed now

index.php
=> added prel=1 to logout

index.php
=> Disabled vpn det

pages/upload2.php
Small changes on upload, added animation
=> Small changes on upload, added animation

include/header-banner.php
Fixed small fill issue to fix mobal bug
=> Fixed small fill issue to fix mobal bug

include/header-normal.php
Changed logged in state on header
=> Changed logged in state on header

index.php
=> Added minifier back

include/footer-normal.php, include/header-normal.php, pages/language.php
=> Small changes

README.md, index.php, lock.php
Changed certain assets to external domain, NOT ALL!
=> Changed certain assets to external domain, NOT ALL!

error/400/401.html, error/400/403.html, error/400/404.html, include/cModal.html
=> Changed error page 401-404

.htaccess
Changed header policy to allow appending domains
=> Changed header policy to allow appending domains

index.php
=> added arc to cookie consent

index.php
=> added infolinks to consent

error/400/401.html, error/400/403.html, error/400/404.html, error/400/408.html, error/400/429.html, error/400/444.html, error/500/500.html, error/500/502.html, error/500/503.html, error/proxy/index.php, include/footer-normal.php, include/header-normal.php, languages/NO.php, static-assets/css/error-document.css, static-assets/css/index.css
=> Fredney revert revert

languages/DE-CH.php, languages/DE-DE.php, languages/IL.php, languages/IT.php, languages/NL.php, languages/NO.php, languages/PL.php, languages/US.php, languages/ZH-CN.php, languages/ZH-HK.php, languages/ZH-TW.php, pages/.php
Added purchase to lang, added ads card for london studios
=> Added purchase to lang, added ads card for london studios

index.php, pages/.php, pages/ref.php
=> Added ad tracking
